### ISSUE TITLE
windows 7 效果不对

### ISSUE THREAD

**Issue by vioulo** [KaiOrange/touchbar-emoji#1]
看到的都是方块，这样的话应该怎么弄？

**Comment by KaiOrange** [comment]
@vioulo 貌似Win7对Emoji支持的不够好 我回去后再研究研究 争取下周一之前把这问题搞定

**Comment by KaiOrange** [comment]
@vioulo 我提交了一笔代码，替换掉了win7支持不够友好的emoji 由于系统的限制 win7的emoji是老式的黑色线条表情 所以win7的效果看上去不是那么炫酷

下载地址：
[MacOS](http://touchbar-emoji.cn-bj.ufileos.com/touchbar-emoji-darwin-x64.zip)

[WindowsOS 安装版](http://touchbar-emoji.cn-bj.ufileos.com/touchbar-emoji-Setup-win32.zip)

[WindowsOS 免安装版](http://touchbar-emoji.cn-bj.ufileos.com/touchbar-emoji-win32-x64.zip)

**Comment by vioulo** [comment]
我下载了 windows 的免安装版的，还是原来的那样子 :crying_cat_face:

**Comment by KaiOrange** [comment]
@vioulo 兄弟 win7兼容性问题已经全面解决 再也不用看到小方块了😤

**Comment by vioulo** [comment]
> @vioulo 兄弟 win7兼容性问题已经全面解决 再也不用看到小方块了

你骗人，你个糟老头子，这不是 Emoji，且都一样的 :dog: 
![Snipaste_2019-10-21_16-22-03](https://user-images.githubusercontent.com/27475937/67188546-2301e100-f41f-11e9-943e-da4cf9057383.png)

**Comment by KaiOrange** [comment]
@vioulo 哈哈 windows系统的emoji就是这个样子 因为版权问题 Windows看到的和安卓和苹果的看到的都略微有点不一样 另外鼠标放到屏幕的最左边 会有一个窗口 可以更换emoji 和 设置等操作
